name: OnPaper Blazor WebAssembly Deployment

on:
  push:
    branches:
      - main

env:
  DOTNET_CORE_VERSION: 8.0.x
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnv20240830003908
  RESOURCE_GROUP: OnPaper
  CONTAINER_REGISTRY_NAME: onpaper
  CONTAINER_REGISTRY_LOGIN_SERVER: onpaper.azurecr.io

jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - appsourcepath: OnPaper
            containerappname: onpaper-container-app

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    
    # Might wanna check out azure/container-apps-deploy-action@v1 here

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.OnPaper_USERNAME_660F }}
        password: ${{ secrets.OnPaper_PASSWORD_660F }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ matrix.containerappname }}:latest ${{ matrix.appsourcepath }}
        docker push ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ matrix.containerappname }}:latest

    - name: Deploy to Azure Container Apps
      uses: azure/cli@v1
      with:
        inlineScript: |
          az containerapp update --name ${{ matrix.containerappname }} --resource-group ${{ env.RESOURCE_GROUP }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ matrix.containerappname }}:latest