name: Build and deploy .NET Core application to Azure Container App

on:
  push:
    branches:
    - main
    paths:
      - 'OnPaper-Trade/**'

env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_ENVIRONMENT_NAME: OnPaper-MS-env
  RESOURCE_GROUP: OnPaper
  CONTAINER_REGISTRY_NAME: onpaper
  CONTAINER_REGISTRY_LOGIN_SERVER: onpaper.azurecr.io

jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.managedEnv20240830003908_SPN }}

    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}/OnPaper-Trade
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.OnPaper_USERNAME_660F }}
        acrPassword: ${{ secrets.OnPaper_PASSWORD_660F }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/onpaper-trade:${{ github.sha }}
        containerAppName: onpaper-trade
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
