name: Build and deploy OnPaper Blazor WebAssembly to Azure Container App

on:
  push:
    branches:
      - main

env:
  DOTNET_CORE_VERSION: 8.0.x
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnv20240830003908
  RESOURCE_GROUP: OnPaper
  CONTAINER_REGISTRY_NAME: onpaper
  CONTAINER_REGISTRY_LOGIN_SERVER: onpaper.azurecr.io

jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - appsourcepath: OnPaper
            containerappname: onpaper-container-app
          - appsourcepath: OnPaper/OnPaper.Client
            containerappname: onpaper-client-container-app

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Display directory structure
      run: |
        ls -R OnPaper

    - name: Restore dependencies
      run: |
        dotnet restore ${{ matrix.appsourcepath }}

    - name: Build solution
      run: |
        dotnet build ${{ matrix.appsourcepath }} -c Release --no-restore

    - name: Publish project
      run: |
        dotnet publish ${{ matrix.appsourcepath }} -c Release -o publish --no-build

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.managedEnv20240830003908_SPN }}

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}/publish
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.OnPaper_USERNAME_660F }}
        acrPassword: ${{ secrets.OnPaper_PASSWORD_660F }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ matrix.containerappname }}:${{ github.sha }}
        containerAppName: ${{ matrix.containerappname }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
